service: resume-cli

frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

custom:
  tableName:
    Ref: ResumeTable

functions:
  importResume:
    handler: functions/upload-resume.handler
    events:
      - http:
          path: resume
          method: post
    environment:
      DYNAMODB_TABLE_NAME: !Ref ResumeTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource:
          - !GetAtt ResumeTable.Arn
          - !Sub "${ResumeTable.Arn}/index/*"

  getResume:
    handler: functions/get-full-resume.handler
    events:
      - http:
          path: /resume/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
    environment:
      DYNAMODB_TABLE_NAME: !Ref ResumeTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - !GetAtt ResumeTable.Arn
          - !Sub "${ResumeTable.Arn}/index/*"
      

resources:
  Resources:
    ResumeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE